AccServerAdmin.Service/Pages/Acknowledgments.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace AccServerAdmin.Service.Pages
{
    public class AcknowledgmentsModel : PageModel
    {
        public void OnGet()
        {

        }
    }
}

AccServerAdmin.Service/Pages/Error.cshtml.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace AccServerAdmin.Service.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

AccServerAdmin.Service/Pages/Index.cshtml.cs
using AccServerAdmin.Application;
using AccServerAdmin.Application.AppSettings;
using AccServerAdmin.Application.Servers.Queries;
using AccServerAdmin.Domain;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AccServerAdmin.Application.Results.Queries;

namespace AccServerAdmin.Service.Pages
{
    public class IndexModel : PageModel
    {
        private readonly IGetServerListQuery _getServerListQuery;
        private readonly IProcessManager _processManager;
        private readonly IGetAppSettingsQuery _getAppSettingsQuery;
        private readonly IGetImportableResultsQuery _getImportableResultsQuery; 

        public IndexModel(
            IProcessManager processManager,
            IGetAppSettingsQuery getAppSettingsQuery,
            IGetServerListQuery getServerListQuery,
            IGetImportableResultsQuery getImportableResultsQuery)
        {
            _processManager = processManager;
            _getAppSettingsQuery = getAppSettingsQuery;
            _getServerListQuery = getServerListQuery;
            _getImportableResultsQuery = getImportableResultsQuery;
        }

        [BindProperty]
        public IEnumerable<DashItem> DashItems { get; private set; }

        public async Task OnGetAsync()
        {
            var settings = await _getAppSettingsQuery.Execute();
            var servers = await _getServerListQuery.Execute();
            
            var items = servers.Select(async s => new DashItem
            {
                Server = s,
                ProcessInfo = _processManager.ServerProcesses.FirstOrDefault(p => p.ServerId == s.Id),
                HasImportableResults = await _getImportableResultsQuery.Execute(s.Id)
            }).ToList();

            DashItems = await Task.WhenAll(items);
            Globals.NeedsConfiguring = settings is null;
        }

        public async Task<ActionResult> OnPostStartServerAsync(Guid serverId)
        {
            await _processManager.StartServerAsync(serverId);
            return new RedirectResult("Index");
        }

        public ActionResult OnPostStopServer(Guid serverId)
        {
            _processManager.StopServer(serverId);
            return new RedirectResult("Index");
        }
    }
}

AccServerAdmin.Service/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace AccServerAdmin.Service.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

AccServerAdmin.Service/Pages/Acknowledgments.cshtml
@page
@model AccServerAdmin.Service.Pages.AcknowledgmentsModel
@{
    ViewData["Title"] = "Acknowledgments";
}


<section class="dashboard-counts section-padding">

    <div class="container-fluid">
        
        <header> 
            <h1 class="h3 display">Acknowledgments</h1>
        </header>        

        <div class="row d-flex">

            <div class="col-lg-4">
                <div class="card income text-center">
                    <div class="row d-flex align-items-center">
                        <div class="title text-center">
                            <p>Developer: Gavin Uttley</p>
                            <p>Website template Design by <a href="https://bootstrapious.com/p/bootstrap-4-dark-admin" class="external">Bootstrapious</a></p>
                            <p>Graphics: Stephen Haley, Chris Crossman</p>
                            <p>
                                Testing: The Simsport racing crew!
                                <ul>
                                    <li>Steve Proudley</li>
                                    <li>Stephen Haley</li>
                                    <li>Chris Crossman</li>
                                    <li>Chris Pinchbeck</li>
                                    <li>Arron Walker</li>
                                </ul>
                            </p>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>
</section>

AccServerAdmin.Service/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Dashboard - ACC Server Admin";
}

<div class="page-header">
    <div class="container-fluid">
        <h2 class="h5 no-margin-bottom">Dashboard</h2>
    </div>
</div>

<section class="no-padding-top no-padding-bottom">
    <div class="container-fluid">

        @if (Globals.NeedsConfiguring)
        {
            <div class="row">
                <div class="col-lg-6">
                    <div class="card">
                        <div class="card-header d-flex align-items-center">
                            <h4>Configuration required</h4>
                        </div>
                        <div class="card-body">
                            <p>Before using this tool you must setup the directory configuration in the <a asp-area="Configuration" asp-page="/Settings">SETTINGS</a></p>
                        </div>
                    </div>
                </div>
            </div>
        }
        else if (!Model.DashItems.Any())
        {
            <div class="row">
                <div class="col-lg-6">
                    <div class="card">
                        <div class="card-header d-flex align-items-center">
                            <h4>No Servers Configured</h4>
                        </div>
                        <div class="card-body">
                            <p>Create a new server <a asp-area="Configuration" asp-page="/Servers/Add">HERE</a></p>
                        </div>
                    </div>
                </div>
            </div>
        }
        else
        {
            <!--
            <div class="row">
                <partial name="_DashboardToolsPartial" />
            </div>
            -->

            <div class="row">
                @foreach (var item in Model.DashItems)
                {
                    <partial name="_ServerCardPartial" model="@item" />
                }
            </div>
        }
    </div>
</section>

AccServerAdmin.Service/Pages/_DashboardToolsPartial.cshtml
    <div class="col-md-6 mb-4">
        <div class="card h-100">
            <div class="card-header">Dashboard Tools</div>
            <div class="card-body">

                <form method="post" >
                    <p class="card-text">
                        
                        
                    </p>
                </form>
            </div>
        </div>
    </div>

AccServerAdmin.Service/Pages/_ServerCardPartial.cshtml
@using AccServerAdmin.Domain
@model AccServerAdmin.Domain.DashItem


    <div class="col-md-3 mb-4">
        <div class="card h-100">
            <div class="card-header">@Model.Server.Name</div>
            <div class="card-body">

                <form method="post" >
                    <p class="card-text">
                        Track: @ListData.Tracks[Model.Server.EventCfg.Track]<br />
                        @if (Model.ProcessInfo != null)
                        {
                            <small>Started: @Model.ProcessInfo?.ProcessInfo?.StartTime;</small><br />
                            <small>PID: @Model.ProcessInfo?.ProcessInfo?.Id;</small><br />

                        }

                        <div class="form-group">

                            <a class="btn btn-primary" asp-area="Configuration" asp-page="/Servers/Edit" asp-route-Id=" @Model.Server.Id">Edit</a>

                            @if (Model.ProcessInfo == null)
                            {

                                <button type="submit" class="btn btn-success" asp-route-serverId="@Model.Server.Id" asp-page-handler="StartServer">Start</button>
                            }
                            else
                            {
                                <button type="submit" class="btn btn-danger" asp-route-serverId="@Model.Server.Id" asp-page-handler="StopServer" onclick="return confirm('Are you sure you want to STOP this server?');">Stop</button>
                            }

                            @if (Model.HasImportableResults)
                            {
                                <a class="btn btn-primary" asp-area="Configuration" asp-page="/Tools/ImportResults" asp-route-Id=" @Model.Server.Id">Import Results</a>
                            }

                        </div>

                    </p>
                </form>
            </div>
        </div>
    </div>