AccServerAdmin.Service/Areas/Configuration/Pages/Drivers/Delete.cshtml.cs
using System;
using System.Threading.Tasks;
using AccServerAdmin.Application.Drivers.Commands;
using AccServerAdmin.Application.Drivers.Queries;
using AccServerAdmin.Domain.AccConfig;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace AccServerAdmin.Service.Areas.Configuration.Pages.Drivers
{
    public class DeleteDriverModel : PageModel
    {
        private readonly IGetDriverByIdQuery _getDriverByIdQuery;
        private readonly IDeleteDriverCommand _deleteDriverCommand;

        public DeleteDriverModel(
            IGetDriverByIdQuery getDriverByIdQuery,
            IDeleteDriverCommand deleteDriverCommand)
        {
            _getDriverByIdQuery = getDriverByIdQuery;
            _deleteDriverCommand = deleteDriverCommand;
        }

        [BindProperty]
        public Driver Driver { get; set; }

        public async Task OnGetAsync(Guid id)
        {
            Driver = await _getDriverByIdQuery.Execute(id);
        }

        public async Task<IActionResult> OnPostAsync()
        {
            await _deleteDriverCommand.Execute(Driver.Id);
            return RedirectToPage("./List");
        }

    }
}

AccServerAdmin.Service/Areas/Configuration/Pages/Drivers/Edit.cshtml.cs
using System;
using System.Threading.Tasks;
using AccServerAdmin.Application.Drivers.Commands;
using AccServerAdmin.Application.Drivers.Queries;
using AccServerAdmin.Application.Exceptions;
using AccServerAdmin.Domain;
using AccServerAdmin.Domain.AccConfig;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace AccServerAdmin.Service.Areas.Configuration.Pages.Drivers
{
    public class EditDriverModel : PageModel
    {
        private readonly IGetDriverByIdQuery _getDriverByIdQuery;
        private readonly ICreateDriverCommand _createDriverCommand;
        private readonly IUpdateDriverCommand _updateDriverCommand;

        public EditDriverModel(
            IGetDriverByIdQuery getDriverByIdQuery,
            ICreateDriverCommand createDriverCommand,
            IUpdateDriverCommand updateDriverCommand)
        {
            _getDriverByIdQuery = getDriverByIdQuery;
            _createDriverCommand = createDriverCommand;
            _updateDriverCommand = updateDriverCommand;
        }

        [BindProperty]
        public Driver Driver { get; set; }

        public SelectList DriverTypes { get; set; }

        private void BuildBindingLists()
        {
            DriverTypes = new SelectList(ListData.DriverTypes, "Key", "Value", Driver.DriverCategory);
        }

        public async Task OnGetAsync(Guid id)
        {
            Driver = id == Guid.Empty
                     ? new Driver() 
                     : await _getDriverByIdQuery.Execute(id);

            BuildBindingLists();
        }

        public async Task<IActionResult> OnPostAsync()
        {
            if (ModelState.IsValid)
            {
                try
                {
                    if (Driver.Id == Guid.Empty)
                    {
                        await _createDriverCommand.Execute(Driver);
                    } 
                    else 
                    {
                        await _updateDriverCommand.Execute(Driver);
                    }
                }
                catch (SteamIdNotUniqueException nex)
                {
                    ModelState.AddModelError("Driver.PlayerId", nex.Message);
                }
                catch (EmptyDirectoryException eex)
                {
                    ModelState.AddModelError(string.Empty, eex.Message);
                }
            }

            if (!ModelState.IsValid)
            {
                BuildBindingLists();
                return Page();
            }
            
            return Redirect("List");
        }

    }
}

AccServerAdmin.Service/Areas/Configuration/Pages/Drivers/List.cshtml.cs
using System.Collections.Generic;
using System.Threading.Tasks;
using AccServerAdmin.Application.Drivers.Queries;
using AccServerAdmin.Domain.AccConfig;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace AccServerAdmin.Service.Areas.Configuration.Pages.Drivers
{
    public class DriverListModel : PageModel
    {
        private readonly IGetDriverListQuery _getDriverListQuery;

        public DriverListModel(IGetDriverListQuery getDriverListQuery)
        {
            _getDriverListQuery = getDriverListQuery;
        }

        [BindProperty]
        public IEnumerable<Driver> Drivers { get; set; }

        public async Task OnGetAsync()
        {
            Drivers = await _getDriverListQuery.Execute();
        }
    }
}

AccServerAdmin.Service/Areas/Configuration/Pages/Servers/Add.cshtml.cs
using System.Threading.Tasks;
using AccServerAdmin.Application.Exceptions;
using AccServerAdmin.Application.Servers.Commands;
using AccServerAdmin.Domain;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace AccServerAdmin.Service.Areas.Configuration.Pages.Servers
{
    public class AddServerModel : PageModel
    {
        private readonly ICreateServerCommand _createServerCommand;

        public AddServerModel(ICreateServerCommand createServerCommand)
        {
            _createServerCommand = createServerCommand;
        }

        [BindProperty]
        public Server Server { get; set; }

        public async Task<IActionResult> OnPostAsync()
        {
            if (ModelState.IsValid)
            {
                try
                {
                    Server = await _createServerCommand.Execute(Server.Name);
                }
                catch (SteamIdNotUniqueException nex)
                {
                    ModelState.AddModelError("Server.Name", nex.Message);
                }
                catch (EmptyDirectoryException eex)
                {
                    ModelState.AddModelError(string.Empty, eex.Message);
                }
            }

            if (!ModelState.IsValid)
            {
                return Page();
            }
            else
            {
                return Redirect($"Edit?Id={Server.Id}");
            }
        }

    }
}

AccServerAdmin.Service/Areas/Configuration/Pages/Servers/AddEntry.cshtml.cs
using System;
using System.Threading.Tasks;
using AccServerAdmin.Application.Entries.Commands;
using AccServerAdmin.Application.Exceptions;
using AccServerAdmin.Domain.AccConfig;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace AccServerAdmin.Service.Areas.Configuration.Pages.Servers
{
    public class AddEntryModel : PageModel
    {
        private readonly ICreateEntryCommand _createEntryCommand;

        public AddEntryModel(ICreateEntryCommand createEntryCommand)
        {
            _createEntryCommand = createEntryCommand;
        }

        [BindProperty]
        public Entry Entry { get; set; }

        [BindProperty]
        public Guid ServerId { get; set; }

        [BindProperty]
        public Guid EntryListId { get; set; }

        public void OnGet(Guid serverId, Guid entryListId)
        {
            ServerId = serverId;
            EntryListId = entryListId;
        }

        public async Task<IActionResult> OnPostAsync()
        {
            if (ModelState.IsValid)
            {
                try
                {
                    Entry.EntryListId = EntryListId;
                    await _createEntryCommand.Execute(Entry);
                }
                catch (RaceNumberNotUniqueException rex)
                {
                    ModelState.AddModelError("Entry.RaceNumber", rex.Message);
                }
            }

            if (!ModelState.IsValid)
            {
                return Page();
            }
            else
            {
                return Redirect($"EditEntry?serverId={ServerId}&EntryListId={EntryListId}&Id={Entry.Id}");
            }
        }

    }
}

AccServerAdmin.Service/Areas/Configuration/Pages/Servers/Delete.cshtml.cs
using System;
using System.Threading.Tasks;
using AccServerAdmin.Application.Servers.Commands;
using AccServerAdmin.Application.Servers.Queries;
using AccServerAdmin.Domain;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace AccServerAdmin.Service.Areas.Configuration.Pages.Servers
{
    public class DeleteServerModel : PageModel
    {
        private readonly IDeleteServerCommand _deleteServerCommand;
        private readonly IGetServerByIdQuery _getServerByIdQuery;

        public DeleteServerModel(
            IGetServerByIdQuery getServerByIdQuery,
            IDeleteServerCommand deleteServerCommand)
        {
            _getServerByIdQuery = getServerByIdQuery;
            _deleteServerCommand = deleteServerCommand;
        }

        [BindProperty]
        public Server Server { get; set; }

        public async Task OnGetAsync(Guid id)
        {
            Server = await _getServerByIdQuery.Execute(id);
        }

        public async Task<IActionResult> OnPostAsync()
        {
            await _deleteServerCommand.Execute(Server.Id);
            return RedirectToPage("./List");
        }

    }
}

AccServerAdmin.Service/Areas/Configuration/Pages/Servers/DeleteBop.cshtml.cs
using System;
using System.Threading.Tasks;
using AccServerAdmin.Application.Bop.Commands;
using AccServerAdmin.Application.Bop.Queries;
using AccServerAdmin.Domain.AccConfig;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace AccServerAdmin.Service.Areas.Configuration.Pages.Servers
{
    public class DeleteBopModel : PageModel
    {
        private readonly IGetBopByIdQuery _getBopByIdQuery;
        private readonly IDeleteBopCommand _deleteBopCommand;
        
        public DeleteBopModel(
            IGetBopByIdQuery getBopByIdQuery,
            IDeleteBopCommand deleteBopCommand)
        {
            _getBopByIdQuery = getBopByIdQuery;
            _deleteBopCommand = deleteBopCommand;
        }

        [BindProperty]
        public Guid ServerId { get; set; }

        [BindProperty]
        public BalanceOfPerformance Balance { get; set; }

        public async Task OnGetAsync(Guid id, Guid serverId)
        {
            ServerId = serverId;
            Balance = await _getBopByIdQuery.Execute(id);
        }

        public async Task<IActionResult> OnPostAsync()
        {
            await _deleteBopCommand.Execute(Balance.Id);
            return RedirectToPage("./Edit", new { Id = ServerId });
        }

    }
}

AccServerAdmin.Service/Areas/Configuration/Pages/Servers/DeleteEntry.cshtml.cs
using System;
using System.Threading.Tasks;
using AccServerAdmin.Application.Entries.Commands;
using AccServerAdmin.Application.Entries.Queries;
using AccServerAdmin.Domain.AccConfig;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace AccServerAdmin.Service.Areas.Configuration.Pages.Servers
{
    public class DeleteEntryModel : PageModel
    {
        private readonly IGetEntryByIdQuery _getEntryByIdQuery;
        private readonly IDeleteEntryCommand _deleteEntryCommand;
        
        public DeleteEntryModel(
            IGetEntryByIdQuery getEntryByIdQuery,
            IDeleteEntryCommand deleteEntryCommand)
        {
            _getEntryByIdQuery = getEntryByIdQuery;
            _deleteEntryCommand = deleteEntryCommand;
        }

        [BindProperty]
        public Entry Entry { get; set; }

        [BindProperty]
        public Guid ServerId { get; set; }

        public async Task OnGetAsync(Guid id, Guid serverId)
        {
            ServerId = serverId;
            Entry = await _getEntryByIdQuery.Execute(id);
        }

        public async Task<IActionResult> OnPostAsync()
        {
            await _deleteEntryCommand.Execute(Entry.Id);
            return RedirectToPage("./Edit", new { Id = ServerId });
        }

    }
}

AccServerAdmin.Service/Areas/Configuration/Pages/Servers/DeleteSession.cshtml.cs
using System;
using System.Threading.Tasks;
using AccServerAdmin.Application.Sessions.Commands;
using AccServerAdmin.Application.Sessions.Queries;
using AccServerAdmin.Domain.AccConfig;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace AccServerAdmin.Service.Areas.Configuration.Pages.Servers
{
    public class DeleteSessionModel : PageModel
    {
        private readonly IGetSessionByIdQuery _getSessionByIdQuery;
        private readonly IDeleteSessionCommand _deleteSessionCommand;
        

        public DeleteSessionModel(
            IGetSessionByIdQuery getServerByIdQuery,
            IDeleteSessionCommand deleteSessionCommand)
        {
            _getSessionByIdQuery = getServerByIdQuery;
            _deleteSessionCommand = deleteSessionCommand;
        }

        [BindProperty]
        public SessionConfiguration Session { get; set; }

        [BindProperty]
        public Guid ServerId { get; set; }

        public async Task OnGetAsync(Guid id, Guid serverId)
        {
            ServerId = serverId;
            Session = await _getSessionByIdQuery.Execute(id);
        }

        public async Task<IActionResult> OnPostAsync()
        {
            await _deleteSessionCommand.Execute(Session.Id);
            return RedirectToPage("./Edit", new { Id = ServerId });
        }

    }
}

AccServerAdmin.Service/Areas/Configuration/Pages/Servers/EditEntry.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AccServerAdmin.Application.Drivers.Queries;
using AccServerAdmin.Application.Entries.Commands;
using AccServerAdmin.Application.Entries.Queries;
using AccServerAdmin.Application.Exceptions;
using AccServerAdmin.Domain;
using AccServerAdmin.Domain.AccConfig;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace AccServerAdmin.Service.Areas.Configuration.Pages.Servers
{
    public class EditEntryModel : PageModel
    {
        private readonly IGetEntryByIdQuery _getEntryByIdQuery;
        private readonly IUpdateEntryCommand _updateEntryCommand;
        private readonly IGetDriverListQuery _getDriverListQuery;
        private readonly IAddDriverEntryCommand _addDriverCommand;
        private readonly IDeleteDriverEntryCommand _deleteDriverCommand;

        public EditEntryModel(
            IGetEntryByIdQuery getEntryByIdQuery,
            IUpdateEntryCommand updateEntryCommand,
            IGetDriverListQuery getDriverListQuery,
            IAddDriverEntryCommand addDriverCommand,
            IDeleteDriverEntryCommand deleteDriverCommand)
        {
            _getEntryByIdQuery = getEntryByIdQuery;
            _updateEntryCommand = updateEntryCommand;
            _getDriverListQuery = getDriverListQuery;
            _addDriverCommand = addDriverCommand;
            _deleteDriverCommand = deleteDriverCommand;
        }

        [BindProperty] public Guid ServerId { get; set; }

        [BindProperty] public Guid EntryListId { get; set; }

        [BindProperty] public Entry Entry { get; set; }

        public List<Driver> Drivers { get; set; }

        public SelectList CarModels { get; set; }

        private async Task BuildBindingListsAsync()
        {
            var model = Entry?.ForcedCarModel ?? CarModel.NotForced;

            CarModels = new SelectList(ListData.Cars, "Key", "Value", model);

            Drivers = (await _getDriverListQuery.Execute()).ToList();
        }

        public async Task OnGetAsync(Guid serverId, Guid entryListId, Guid id)
        {
            ServerId = serverId;
            EntryListId = entryListId;

            Entry = id == Guid.Empty
                ? new Entry {EntryListId = entryListId}
                : await _getEntryByIdQuery.Execute(id);

            await BuildBindingListsAsync();
        }

        public async Task<IActionResult> OnPostAsync()
        {
            if (Entry.Ballast > 100)
            {
                ModelState.AddModelError("Entry.Ballast", "Ballast maximum is 100KG");
            }

            if (Entry.Restrictor > 20)
            {
                ModelState.AddModelError("(Entry.Restrictor", "Restrictor maximum is 20%");
            }

            if (ModelState.IsValid)
            {
                try
                {
                    Entry.EntryListId = EntryListId;
                    await _updateEntryCommand.Execute(Entry);
                }
                catch (RaceNumberNotUniqueException nex)
                {
                    ModelState.AddModelError("Entry.RaceNumber", nex.Message);
                }
                catch (GridPositionNotUniqueException gex)
                {
                    ModelState.AddModelError("Entry.DefaultGridPosition", gex.Message);
                }
            }

            if (!ModelState.IsValid)
            {
                await BuildBindingListsAsync();
                return Page();
            }

            return Redirect($"Edit?Id={ServerId}");
        }

        public async Task OnGetSelectDriver(Guid serverId, Guid entryListId, Guid entryId, Guid driverId)
        {
            var driverEntry = new DriverEntry {DriverId = driverId, EntryId = entryId};
            await _addDriverCommand.Execute(driverEntry);
            await OnGetAsync(serverId, entryListId, entryId);
        }

        public async Task OnGetRemoveDriver(Guid serverId, Guid entryListId, Guid entryId, Guid driverId)
        {
            var driverEntry = new DriverEntry {DriverId = driverId, EntryId = entryId};
            await _deleteDriverCommand.Execute(driverEntry);
            await OnGetAsync(serverId, entryListId, entryId);
        }
    }
}

AccServerAdmin.Service/Areas/Configuration/Pages/Servers/Add.cshtml
@page
@model AccServerAdmin.Service.Areas.Configuration.Pages.Servers.AddServerModel
@{
    ViewData["Title"] = "Add a new server";
}

<div class="page-header">
    <div class="container-fluid">
        <h2 class="h5 no-margin-bottom">Servers</h2>
    </div>
</div>

<section class="no-padding-top no-padding-bottom">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-6">
                <div class="card">

                    <div class="card-header d-flex align-items-center">
                        <h4>Create New Server</h4>
                    </div>
                    <div class="card-body">
                        <p></p>
                        <form method="post">
                            <div class="form-group">
                                <label asp-for="Server.Name" class="label-material">Server Name</label>
                                <input asp-for="Server.Name" type="text" class="form-control">
                                <span asp-validation-for="Server.Name" class="text-danger"></span>
                            </div>

                            <div class="form-group-material">
                                <div asp-validation-summary="All" class="text-danger"></div>
                            </div>

                            <div class="form-group">
                                <input type="submit" value="Save" class="btn btn-primary">
                            </div>
                        </form>
                    </div>

                </div>
            </div>
        </div>
    </div>
</section>

AccServerAdmin.Service/Areas/Configuration/Pages/Servers/AddEntry.cshtml
@page
@model AccServerAdmin.Service.Areas.Configuration.Pages.Servers.AddEntryModel
@{
    ViewData["Title"] = "Add a new Entry";
}

<div class="page-header">
    <div class="container-fluid">
        <h2 class="h5 no-margin-bottom">Entries</h2>
    </div>
</div>

<section class="no-padding-top no-padding-bottom">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-6">
                <div class="card">

                    <div class="card-header d-flex align-items-center">
                        <h4>Create New Entry</h4>
                    </div>
                    <div class="card-body">
                        <p></p>
                        <form method="post">
                            <div class="form-group">
                                <label asp-for="Entry.RaceNumber" class="label-material">Race Number</label>
                                <input asp-for="Entry.RaceNumber" type="text" class="form-control">
                                <span asp-validation-for="Entry.RaceNumber" class="text-danger"></span>
                            </div>

                            <div class="form-group">
                                <input type="submit" value="Save" class="btn btn-primary">
                            </div>
                        </form>
                    </div>

                </div>
            </div>
        </div>
    </div>
</section>

AccServerAdmin.Service/Areas/Configuration/Pages/Servers/EditEntry.cshtml
@page
@model AccServerAdmin.Service.Areas.Configuration.Pages.Servers.EditEntryModel
@{
    ViewData["Title"] = "Server entry";
}

@section Scripts
{
    <script src="@Url.Content("/js/entry-import.js")"></script>
    <script src="@Url.Content("/vendor/datatables.net/js/jquery.dataTables.js")"></script>
    <script src="@Url.Content("/vendor/datatables.net-bs4/js/dataTables.bootstrap4.js")"></script>
    <script src="@Url.Content("/vendor/datatables.net-responsive/js/dataTables.responsive.min.js")"></script>
    <script src="@Url.Content("/vendor/datatables.net-responsive-bs4/js/responsive.bootstrap4.min.js")"></script>
    <script src="@Url.Content("/js/driverselect-datatable.js")"></script>
}

<div class="page-header">
    <div class="container-fluid">
        <h2 class="h5 no-margin-bottom">Server Entry</h2>
    </div>
</div>

<section class="no-padding-top no-padding-bottom">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-6">
                <div class="card">

                    <div class="card-header d-flex align-items-center">
                        <h4>Edit Entry</h4>
                    </div>

                    <div class="card-body">

                        <form method="post">

                            @Html.HiddenFor(model => model.ServerId)
                            @Html.HiddenFor(model => model.EntryListId)
                            @Html.HiddenFor(model => model.Entry.Id)

                            <div class="form-group row">
                                <label asp-for="Entry.RaceNumber" class="col-sm-2 form-control-label">Race Number</label>
                                <div class="col-sm-10">
                                    <input asp-for="Entry.RaceNumber" type="text" class="form-control">
                                    <span asp-validation-for="Entry.RaceNumber" class="text-danger"></span>
                                </div>
                            </div>

                            <div class="form-group row">
                                <label asp-for="Entry.DefaultGridPosition" class="col-sm-2 form-control-label">Default Grid Position</label>
                                <div class="col-sm-10">
                                    <input asp-for="Entry.DefaultGridPosition" type="text" class="form-control">
                                    <span asp-validation-for="Entry.DefaultGridPosition" class="text-danger"></span>
                                </div>
                            </div>

                            <div class="form-group row">
                                <label asp-for="Entry.ForcedCarModel" class="col-sm-2 form-control-label">Car Model</label>
                                <div class="col-sm-10">
                                    <select asp-for="Entry.ForcedCarModel" asp-items="Model.CarModels" class="form-control">
                                        <option value="">-- Select a Car Type --</option>
                                    </select>
                                </div>
                            </div>

                            <div class="form-group row">
                                <label asp-for="Entry.CustomCar" class="col-sm-2 form-control-label">Custom Car Json</label>
                                <div class="col-sm-10">
                                    <input asp-for="Entry.CustomCar" type="text" class="form-control">
                                    <span asp-validation-for="Entry.CustomCar" class="text-danger"></span>
                                </div>
                            </div>

                            <div class="form-group row">
                                <label asp-for="Entry.Ballast" class="col-sm-2 form-control-label">Ballast KG</label>
                                <div class="col-sm-10">
                                    <input asp-for="Entry.Ballast" type="text" class="form-control">
                                    <span asp-validation-for="Entry.Ballast" class="text-danger"></span>
                                </div>
                            </div>

                            <div class="form-group row">
                                <label asp-for="Entry.Restrictor" class="col-sm-2 form-control-label">Restrictor %</label>
                                <div class="col-sm-10">
                                    <input asp-for="Entry.Restrictor" type="text" class="form-control">
                                    <span asp-validation-for="Entry.Restrictor" class="text-danger"></span>
                                </div>
                            </div>

                            <div class="form-group row">
                                <label class="col-sm-2 form-control-label">&nbsp;</label>
                                <div class="col-sm-10">
                                    <div class="i-checks">
                                        <input asp-for="Entry.ServerAdmin" type="checkbox" class="checkbox-template">
                                        <label asp-for="Entry.ServerAdmin">Server Admin</label>
                                    </div>

                                    <div class="i-checks">
                                        <input asp-for="Entry.OverrideDriverInfo" type="checkbox" class="checkbox-template">
                                        <label asp-for="Entry.OverrideDriverInfo">Override Driver Info</label>
                                    </div>

                                    <div class="i-checks">
                                        <input asp-for="Entry.OverrideCarModelForCustomCar" type="checkbox" class="checkbox-template">
                                        <label asp-for="Entry.OverrideCarModelForCustomCar">Override Car Model</label>
                                    </div>
                                </div>
                            </div>

                            <div class="form-group row">
                                <label class="col-sm-2 form-control-label">Drivers</label>
                                <div class="col-sm-10">
                                    <ul>
                                        @foreach (var driver in Model.Entry.Drivers)
                                        {
                                            <li>
                                                @driver.Fullname
                                                <a asp-page-handler="RemoveDriver"
                                                   asp-route-serverId="@Model.ServerId"
                                                   asp-route-entryListId="@Model.EntryListId"
                                                   asp-route-entryId="@Model.Entry.Id"
                                                   asp-route-driverId="@driver.Id"
                                                   alt="Select @driver.Fullname">Remove Driver</a>
                                            </li>
                                        }
                                    </ul>

                                    <button type="button" data-toggle="modal" data-target="#driverSelector" class="btn btn-primary">Add Driver</button>
                                </div>

                                <partial name="_AddEntryDriverPartial" />
                            </div>

                            <div class="form-group-material">
                                <div asp-validation-summary="All" class="text-danger"></div>
                            </div>

                            <div class="form-group">
                                <input type="submit" value="Save" class="btn btn-primary">
                                <button type="button" onclick="window.history.go(-1); return false;" class="btn btn-primary">Cancel</button>
                            </div>
                        </form>
                    </div>

                </div>

            </div>

        </div>
    </div>
</section>

AccServerAdmin.Service/Areas/Configuration/Pages/Servers/_AddEntryDriverPartial.cshtml
@model AccServerAdmin.Service.Areas.Configuration.Pages.Servers.EditEntryModel


<div id="driverSelector" tabindex="-1" role="dialog" aria-labelledby="driverSelectLabel" aria-hidden="true" class="modal fade text-left">
    <div role="document" class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <strong id="driverSelectLabel" class="modal-title">Driver Selector</strong>
                <button type="button" data-dismiss="modal" aria-label="Close" class="close">
                    <span aria-hidden="true">×</span>
                </button>
            </div>
            <div class="modal-body">
                
                <div class="form-group">
                    <div class="table-responsive">
                        <table id="driverSelectTable" style="width: 100%;" class="table table-striped table-sm">
                            <thead>
                            <tr>
                                <th>Driver</th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach (var driver in Model.Drivers)
                            {
                                <tr>
                                    <td>
                                        <a asp-page-handler="SelectDriver" 
                                           asp-route-serverId="@Model.ServerId" 
                                           asp-route-entryListId="@Model.EntryListId"
                                           asp-route-entryId="@Model.Entry.Id" 
                                           asp-route-driverId="@driver.Id"
                                           alt="Select @driver.Fullname">@driver.Fullname</a>
                                    </td>
                                </tr>
                            }
                            </tbody>
                        </table>
                    </div>
                </div>

            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-primary">Save changes</button>
            </div>
        </div>
    </div>
</div>