AccServerAdmin.Service/Areas/Configuration/Pages/Tools/ImportResults.cshtml.cs
using System;
using System.Threading.Tasks;
using AccServerAdmin.Application.Results.Queries;
using AccServerAdmin.Application.Servers.Queries;
using AccServerAdmin.Domain;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace AccServerAdmin.Service.Areas.Configuration.Pages.Tools
{
    public class ImportResultsModel : PageModel
    {
        private readonly IGetServerByIdQuery _getServerByIdQuery;
        private readonly IResultImporter _resultImporter;
        private readonly ILogger<ImportResultsModel> _logger;

        public ImportResultsModel(
            IGetServerByIdQuery getServerByIdQuery,
            IResultImporter resultImporter,
            ILogger<ImportResultsModel> logger)
        {
            _getServerByIdQuery = getServerByIdQuery;
            _resultImporter = resultImporter;
            _logger = logger;
        }

        [BindProperty]
        public Server Server { get; set; }

        public async Task OnGetAsync(Guid id)
        {
            Server = await _getServerByIdQuery.Execute(id);
        }

        public async Task OnPostImportResultsAsync(Guid id, string serverName)
        {
            try
            {
                await _resultImporter.Execute(id, serverName);
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Exception caught attempting to import users");
            }
        }

    }
}

AccServerAdmin.Service/Areas/Configuration/Pages/Tools/ImportResults.cshtml
@page
@model AccServerAdmin.Service.Areas.Configuration.Pages.Tools.ImportResultsModel

@section Scripts
{
    <script src="@Url.Content("/js/result-import.js")"></script>
}

<div class="page-header">
    <div class="container-fluid">
        <h2 class="h5 no-margin-bottom">Result Import</h2>
    </div>
</div>

<section class="no-padding-top no-padding-bottom">
    <div class="row">
        <div class="col-lg-10">
            <div class="card">

                <div class="card-header">
                    <h4>Import Results - @Model.Server.Name</h4>
                </div>

                <div class="card-body">
                    
                    <form method="post" id="entryImportForm">
                        <button type="submit" id="startImportBtn" class="btn btn-success" asp-route-Id="@Model.Server.Id" asp-route-serverName="@Model.Server.Name" asp-page-handler="ImportResults">Start</button>
                    </form>

                    <div class="table-responsive">
                        <table class="table table-striped table-sm" id="messages">
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>